NIAEFEUP/tts-be

mysql/sql/3_course_unit.sql

Closes #26 
Added sql query to delete from the database all the repeated courses with no subjects associated to.
Exemple:
Licenciatura em Engenharia Informática e Computação is inserted twice in the course table, one row from fcup and one row from feup. The feup course didn't have any subjects associated to it in the course_unit table, so it was deleted.

Delete statement to remove all repeated courses with no subjects

---

mysql/sql/5_clean_database.sql

Closes #34 
Added sql query to delete from the database all the repeated theoretical classes. A theoretical class is considered repeated when there's more than one record with the same 'day', 'duration', 'start_time', 'composed_class_name' and 'course_unit_id' fields.
A script to test this issue will be done later together with issue #31.

Delete statement to remove repeated theoretical classes

---

django/university/urls.py
django/university/views.py
mysql/sql/5_clean_database.sql

This pull request regards a few changes to make the time table selector reliable upon the misleading information that sigarra can provide.

Change API and added cleaning

---

django/university/views.py
mysql/sql/00_schema_mysql.sql

Closes #51 
*Note:* Currently, as the new modifications to the tables and the scrapper are not on the develop branch yet, when you are testing this, it is most likely that the course_unit_year table is empty on the local version of your database and that is probably the reason why if you run this backend version it will not work correctly as it will return an empty array if you're course_unit_year table is also empty.
*For future reference*
In order to address the planned changes in the database, it was necessary to now retrieve information about course units through the course_unit_year table as the same course unit can have more than one curricular year, instead of risking having more than one entry in the database about the same course unit where the only thing different would be the …

Refactor: course_units_api now searches courses and course_units through course_unit_year table

---

docker-compose.yaml

Increased limit of numbers of files that can be simultaneously opened by the tts-be db process/container.
This fixes building tts-be for arch users.

Fixed docker compose configuration for arch

---

django/university/urls.py
django/university/views.py
mysql/sql/00_schema_mysql.sql

A new endpoint was created for the `info` table. This table only has one row. Therefore, only the first row is checked. Currently, this table only has one column `date`.
Closes #71

Endpoint for scrapper info created

---

django/university/views.py

Switched the names from:
```
professors.append({
'professor_id': professor.id,
'professor_acronym': professor.professor_acronym,
'professor_name': professor.professor_name
})
```
to:
```
professors.append({
'id': professor.id,
'acronym': professor.professor_acronym,
'name': professor.professor_name
})
```

Changed the name of the professor model values

---

django/university/response/errors.py
django/university/urls.py
django/university/views.py

This had to be done, since in order to have the paste course options functionality work on the frontend for courses different from the selected ones, we needed a way to retrieve a `CourseInfo` object from the backend and there were no endpoints available for that.

Endpoint to return course unit based on id

---

README.md

Closes #77 
- The command `docker compose build . ` didn't work
- There were references to scripts that no longer exist on the repository (for example, the `build_dev.sh`)

Fixes wrong command on README and more detail on django caveats

---

django/university/controllers/ClassController.py
django/university/views.py

It uses the `prefetch_related` feature in django to speedup class retrieval.
It also prioritizes the use of `map` instead of `for` due to its speed advantage.
It decreased the time by 1 - 1.5 seconds.

Use more django orm features to speed up classes retrieval

---

.github/workflows/niployments.yaml
django/Dockerfile

chore: prepare for niployments

---

django/university/controllers/ClassController.py

In Django, `NUMERIC` fields are parsed into strings instead of floats, which causes problems in frontend since it expects the fields `start_time` and `duration` of the slots to be of `number` type (either `integer` or `float`), like in conflict detection. This PR solves this problem by enforcing the type conversion to `float` when satissfying the request to the `class/` endpoint.

Fix schedule start time and duration types

---

django/Dockerfile
django/requirements.txt

Closes #100 
There is a lot of reported security vulnerabilities because of the outdated versions we keep using in our dependencies.
Moreover, having major dependencies outdated also harms us when we want to use a new feature because we will be restricted by the limitations of versions compatibilities.

Chore: upgraded django and other dependencies

---

docker-compose.yaml

When restart policy is set to always, the docker container will start every time the docker service is initiated (normally, after boot). This policy was used for the pgAdmin and Redis containers.
The problem is that this policy is irrelevant, as the server will always have to be initiated with the scripts and those containers are not set up on the cluster. Also, I noticed that the Redis container, in particular, was consuming a lot of battery power, so this simple change should give a slight boost to your battery life :smiley:

Remove restart policy "always" from containers

---

django/tts_be/settings.py
django/university/routes/auth/Csrf.py
django/university/urls.py
django/university/views.py
nginx/nginx.conf

Currently, in the federated authentication deployed at tts-staging.niaefeup.pt, after a successful login it is redirecting to `/oidc-auth/callback`. 
However, it needs to be `/api/oidc-auth/callback`. This PR fixes it.
It also removes a temporary solution in the local nginx because now we don't need to redirect `/oidc-auth/callback` to `/api/oidc-auth/callback`. **This has nothing to do with the production deployment**, since the only thing that will be deployed to niployments is the django docker image, nothing else.

fix: prod oidc callback invalid url

---

django/university/controllers/SigarraController.py
django/university/exchange/utils.py
django/university/routes/MarketplaceExchangeView.py
django/university/routes/auth/InfoView.py
django/university/routes/student/exchange/StudentSentExchangesView.py
django/university/routes/student/schedule/StudentScheduleView.py

The year change from 2024 to 2025 broke the logic of creating the `semana_ini` and `semana_fim`.
Currently, the first semester is harcoded, but that is ok since we are going to change the url endpoint we will be fetching the schedule from.

fix: schedule api broken date

---

postgres/sql/00_schema_postgres.sql

Because of the `user course units` table, it was complaning that the `id` constraint class was not unique. 
In fact it was not, but since the id of a class can be unique, this fixes the error when running the backend after cleaning the data or for the first time by adding the `UNIQUE` constraint to the `class` table

fix: added unique constraint that was missing to class id

---

django/tts_be/asgi.py
django/university/socket/participant.py
django/university/socket/session.py
django/university/socket/sessionsserver.py
django/university/socket/views.py
django/university/views.py

This pull request is closely related to [frontend pull request #356](https://github.com/NIAEFEUP/tts-fe/pull/356).
- Supports multiple collaboration sessions using SocketIO rooms, they are saved in the database and can be accessed again if they haven't expired
- One user creates the session and can then share the access link with others
- Usernames are taken from authenticated users, or, as a fallback, randomly generated with an AdjectiveAnimal combination (but can be changed later)
- Username information is shared in the session as an example of real-time updates
- For testing purposes, ping messages are broadcast in the room (can be seen in browser console)

Collaborative Sessions - Actually create a session [Backend]

---

django/university/controllers/StudentController.py
django/university/routes/exchange/card/metadata/ExchangeCardMetadataView.py
django/university/routes/student/schedule/StudentScheduleView.py
django/university/serializers/ClassSerializer.py

In the backend, we put the name of the class of the student in the response. It is unfeasible to go on about fetching the classes of each user of the all of the possible students to select from when the user is choosing between requests.

feature: automatic student class fill

---

django/university/controllers/ExchangeController.py
django/university/routes/student/exchange/StudentReceivedExchangesView.py

If the exchange was accepted, the pending motive as being `None` and that was crashing the backend.

fix: if user has already accepted direct exchange the backend does not crash

---

django/university/routes/MarketplaceExchangeView.py

The problem was that while creating an `UrgentRequest`, we were not specifying nor the data nor the admin state of the request

fix: urgent requests with motive not creating

---

django/university/controllers/SigarraController.py

For testing purposes, this extends the first semester to also include february because second semester schedules are not out yet

chore: extend first semester

---

django/university/routes/exchange/DirectExchangeView.py

Instead of showing not accepted exchanges, it only shows to admins direct exchanges that were accepted.

fix: admin direct exchange show accepted only

---

django/university/controllers/AdminRequestFiltersController.py
django/university/routes/course_unit/CourseUnitEnrollmentView.py
django/university/routes/exchange/AdminExchangeRequestMarkAwaitingInformationView.py
django/university/routes/exchange/AdminRequestAwaitingInformationView.py
django/university/routes/exchange/DirectExchangeView.py
django/university/routes/exchange/ExchangeUrgentView.py
django/university/serializers/CourseUnitEnrollmentsSerializer.py
django/university/urls.py

- Admins can now select multiple state filters at the same time
- Admins can now mark request as awaiting for information

feat: admins can mark requests as awaiting for information

---

django/.env.example
django/university/controllers/ExchangeController.py
django/university/controllers/SigarraController.py
django/university/exchange/utils.py
django/university/routes/MarketplaceExchangeView.py

Closes #155 
This PR also solves some bugs that we had with the class overlap logic. To test this, do not forget to set the `T_CLASS_CONFLICTS` boolean in `django/.env.dev`

Enable conflicts with theoretical classes

---

django/tts_be/settings.py

When a server error occurs in the server, because `DEBUG = False` due to security reasons, we need to enable logging to a file inside of the container so we can debug critical errors better that happen in production but non in our local environments.

feat: enable prod loggin

---

django/university/routes/MarketplaceExchangeView.py
django/university/routes/student/schedule/StudentScheduleView.py

Always populating student course units and student course metadata was slowing down the schedule endpoint thus making visual glitches due to the delay of responding to appear
StudentCourseUnits will be updated in the actions that need to update them, such as accepting a direct exchange instead of always.

fix: schedule loading is not slow anymore to the point of visual glitches

---

django/university/routes/exchange/DirectExchangeView.py

jwt with dots is messing up the nginx in the production build on the frontend

fix: base64 encode jwt in url
